### ISSUE TITLE
Convergence problems in the tutorial singlepoint naca0012 case

### ISSUE THREAD

**Issue by shlomyshitrit** [mdolab/MACHtutorial#15]
Hi,
I encounter several problems while running the single point optimization problem naca0012 which is part of the machtutorial package.
I  think that most of the problems results in an incompatibility between the machtutorial package and the adflow and python subroutines. 
Some of the problems I encoubtered are as follows:
1. In the airfoil_opt.py file: pywarp should be idwarp, MBMesh should be USMesh, 'snopt' optimizer does not exist. The only optimizer that runs is Alpso.
2. Running the problem with Alpso does not reach convergence, and no logical optimization is done. Passing nearly 400 optimization cycles and it seems lost. 
3. The pyHyp subroutine to construct a volume cgns mesh end with error. cgns_utils does not exist. I guess there is another cgns python package that must be uploaded to github, since cgns_utils is not part of the formal cgns tools.

That is for now. I was in contact with John Jasa recently and he suggested to open this issue. Thank you very much and I hope to here from you soon.
Shlomy

**Comment by A-Gray-94** [comment]
Hi Shlomy, in answer to your questions:

1. You are correct about idwarp and USMesh, we are currently in the process of updating this in the tutorials (see https://github.com/mdolab/MACHtutorial/pull/16) but as I guess you have noticed, you can just do a straight swap of idwarp for pywarp and USMesh for MBMesh for now.
2. SNOPT is a commercial algorithm and so does not come packaged with pyOptSparse. If you are in academia you can get a trial version [here](url), but I have no experience setting up this version to work with pyOptSparse. I would highly recommend against using ALPSO, it is a stochastic rather than gradient based optimiser and so will almost certainly require far too many function evaluations to be practical. Have you tried using SLSQP? That is the closest freely available algorithm to SNOPT.
3. cgns_utils was recently made public, you can find it [here](https://github.com/mdolab/cgnsutilities). If you still get the same error after installation then try running the script from the terminal, I got the same error when running the script in my IDE but not from the terminal.

Hope this helps!

Ali
